//action for tracks
export const START_FETCHING_TRACKS = 'START_FETCHING_TRACKS';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE';

// acitons for UI
export const START_FADING = 'START_FADING';
export const STOP_FADING = 'STOP_FADING';

//actions for song
export const START_FETCH_SONG = 'START_FETCH_SONG';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';
