//action for tracks
export const START_FETCHING_TRACKS = 'START_FETCHING_TRACKS';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILUREE';
export const FETCH_MORE_TRACKS_SUCCESS = 'FETCH_MORE_TRACKS_SUCCESS';
export const START_FETCHING_MORE_TRACKS = 'START_FETCHING_MORE_TRACKS';
export const CLEAR_TRACKS = 'CLEAR_TRACKS';
// acitons for UI
export const START_FADING = 'START_FADING';
export const STOP_FADING = 'STOP_FADING';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_SHOW_ANALYZER = 'SET_SHOW_ANALYZER';
export const SET_COLOR = 'SET_COLOR';
export const CLEAR_COLOR = 'CLEAR_COLOR';

//actions for song
export const START_FETCH_SONG = 'START_FETCH_SONG';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';

//actions for player
export const UPDATE_LYRIC = 'UPDATE_LYRIC';
export const UPDATE_PLAYED_PERCENT = 'UPDATE_PLAYED_PERCENT';
export const UPDATE_LYRIC_PERCENT = 'UPDATE_LYRIC_PERCENT';

//action for queue
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const REPLACE_QUEUE = 'REPLACE_QUEUE';
export const CLEAR_QUEUE = 'CLEAR_QUEUE';
export const REMOVE_SONG_FROM_QUEUE = 'REMOVE_SONG_FROM_QUEUE';
